### ISSUE TITLE
response.format for .pdf is changed from "pdf" to "all" after installing mail plugin

### ISSUE THREAD

**Issue by rlovtangen** [grails3-plugins/mail#10]
````
$ sdk use grails 3.0.8
$ grails create-app pdf308
$ cd pdf308
$ grails create-controller Foo
$ echo "\${response.format}" > grails-app/views/foo/index.gsp
$ grails run-app
````
open http://localhost:8080/foo/index.pdf
Output is: `pdf`

Add mail plugin to build.gradle:
````
compile "org.grails.plugins:mail:2.0.0.RC2"
````
run-app and reload page. Output is now: `all`

This seems to be the case with Grails 3.0.8 and later. With Grails 3.0.7 and earlier, output is `pdf` both before and after installing plugin.
Both 2.0.0.RC1  and 2.0.0.RC2 is affected.

Unfortunately, this is causing issues in wkhtmltopdf plugin, see rlovtangen/grails-wkhtmltopdf#15

**Comment by PatrickHuetter** [comment]
+1 same problem here with latest grails 3.0.11

**Comment by sbglasius** [comment]
I can not reproduce this issue on 3.0.14 and the upcoming 2.0.0 release

**Comment by rlovtangen** [comment]
Tested OK in both Grails 3.0.8 and 3.0.14 with mail plugin 2.0.0.RC4
Version 2.0.0.RC2 fails in both Grails 3.0.8 and 3.0.14 so it seems to have been resolved by a change between RC2 and RC4.
