### ISSUE TITLE
Cannot mix 3.0.0.RC2 Plugins with 3.0.0 app

### ISSUE THREAD

**Issue by robbugh** [grails3-plugins/mail#2]
It does not appear you can mix a Grails v3.0.0 app with Grails v3.0.0.RC2 plugins

To reproduce:
  - Create a Grails 3.0.0 app
  - Include a dependency on a plugin built with Grails 3.0.0.RC2. (Also, ensure gradle.properties `grailsVersion=3.0.0.RC2`)
  - Start the app and notice the following exception is thrown:

`java.lang.ClassNotFoundException: reactor.bus.Observable`

**Comment by davydotcom** [comment]
Not sure if this is the right place for this issue. The mail plugin has been compiled against 3.0.0

**Comment by robbugh** [comment]
Correct. It was updated to Grails 3.0.0 after I posted this issue, but the issue still remains with any plugin still at RC2. However, given that we are talking about mixing release and pre-release code it is probably not worth pursuing.
