### ISSUE TITLE
grails3 override username

### ISSUE THREAD

**Issue by noemiebolo** [grails3-plugins/mail#21]
Hello,

I would like to override grails.mail.username and grails.mail.password in the file application-development.yml.

In application.yml :
grails:
mail:
username: user
password: pass

In application-development.yml :
grails:
mail:
username: new-user
password: new-pass

I expect, in a development mode, to get new-user and new-pass as values but I only get empty strings in mailSender object (from mailService).

Can someone explain me why ?
Thanks
Noémie

**Comment by ujjwol05** [comment]
create a groovy script file named as application.groovy and here is the config :
grails {
	mail {
		host = "smtp.gmail.com"
		port = 465
		username = "abc@gmail.com"
		password = "password"
		props = ["mail.smtp.auth":"true",
				 "mail.smtp.socketFactory.port":"465",
				 "mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory",
				 "mail.smtp.socketFactory.fallback":"false"]
	}
}

**Comment by noemiebolo** [comment]
answer in https://github.com/gpc/grails-mail/issues/36.
