### ISSUE TITLE
Option to set subject and text by message code

### ISSUE THREAD

**Issue by davidkron** [grails3-plugins/mail#22]
I think it would be useful to have the option to set a mail's subject and text content by providing a message code. As a developer, the advantage is that I don't have to include the messageSource myself and with the already available "locale" option subject and text could be translated to the correct locale.

Code example:

mailService.sendMail {
    locale user.languageForCorrespondence
    subject 'mail.summary.subject'
    text 'mail.summary.text'
}

**Comment by sbglasius** [comment]
In my opinion this is not a responsibility for the _mail_ plugin.

**Comment by davidkron** [comment]
As some time passed since I had this idea I also think it is not a good idea anymore.
Also it is not that hard to implement a custom wrapper service or helper method if one really needs this functionality.
