### ISSUE TITLE
No signature of method: myController.mutipart() is applicable for argument types: (java.lang.Boolean) values: [true]

### ISSUE THREAD

**Issue by rodrigosalinas** [grails3-plugins/mail#29]
Hi, I'm trying version 2.0.0 and Grails 3.3.1.

Using this code in myController I get the error in the subject:

```
mailService.sendMail {
   mutipart true
   to 'address'
   cc 'anotherAddress'
   subject 'Subject'
   html 'content'
   attach pdf.name, "application/pdf", pdf
}
```

Please help. Thank you very much in advance.

**Comment by rodrigosalinas** [comment]
Sorry. Was a mispell of multipart.

**Comment by hunterino** [comment]
This was actually a bug in the documentation.  In the examples it uses mutipart, instead of multipart.  I'm looking for the documentation now, to fix it.
