### ISSUE TITLE
'to' value limit? send multiple emails

### ISSUE THREAD

**Issue by barcelona23** [grails3-plugins/mail#35]
I'm wondering if there is a limit for the TO value.
I want to send multiple emails at send time using same smtp config.
I have a list with all 'to's

```
toList.each { String emailTo, String name ->
	String nameTo = name ?: emailTo
	sendMail {
		to emailTo
		subject 'Test #1'
		html view: "/mail/simple", model: [name: nameTo]
	}
}
```

Any limitation?

**Comment by sbglasius** [comment]
If there is a limitation that would be on the underlying Java Mail api, not the _mail_ plugin.
