### ISSUE TITLE
Remove dataSource items from application.yml

### ISSUE THREAD

**Issue by nusairat** [grails3-plugins/mail#6]
This should be removed since the application does not require any H2 datasource.

Furthermore this causes an issue if your application DOESNT have nor want H2 references.

**Comment by jeffbrown** [comment]
I think this was addressed with https://github.com/grails3-plugins/mail/pull/7

**Comment by jeffbrown** [comment]
Should all of the `dataSource` settings be removed from `application.yml`?  I think probably yes.

**Comment by nusairat** [comment]
I'd think so. If the app isn't going to use it no reason to have it IMHO.
